Class {
	#name : #GeoBRFileReferences,
	#superclass : #Object,
	#category : #'Geo-Birthright-Cerilia-FileReferences'
}

{ #category : #accessing }
GeoBRFileReferences class >> charactersAnuire [

	^ '/home/georges/Geo BR Atlas/data/Characters - Anuire.csv'
]

{ #category : #accessing }
GeoBRFileReferences class >> deities [

	^ '/home/georges/Geo BR Atlas/data/Deities.csv'
]

{ #category : #accessing }
GeoBRFileReferences class >> domains [

	^ '/home/georges/Geo BR Atlas/data/domains.xml'
]

{ #category : #accessing }
GeoBRFileReferences class >> domainsAnuire [

	^ '/home/georges/Geo BR Atlas/data/Domains - Anuire.csv'
]

{ #category : #accessing }
GeoBRFileReferences class >> mountains [

	^ '/home/georges/Geo BR Atlas/data/mountains.svg'
]

{ #category : #accessing }
GeoBRFileReferences class >> paths [

	^ '/home/georges/Downloads/Cerilia Map v1.13_scaled002.svg'
]

{ #category : #accessing }
GeoBRFileReferences class >> provinceDataEasternMarches [

	^ '/home/georges/Geo BR Atlas/data/Provinces Data - Anuire - Eastern Marches.csv'
]

{ #category : #accessing }
GeoBRFileReferences class >> provinceDataHearthlands [

	^ '/home/georges/Geo BR Atlas/data/Provinces Data - Anuire - Heartlands.csv'
]

{ #category : #accessing }
GeoBRFileReferences class >> provinceDataNorthernMarches [

	^ '/home/georges/Geo BR Atlas/data/Provinces Data - Anuire - Northern Marches.csv'
]

{ #category : #accessing }
GeoBRFileReferences class >> provinceDataSouthernCoast [

	^ '/home/georges/Geo BR Atlas/data/Provinces Data - Anuire - Southern Coast.csv'
]

{ #category : #accessing }
GeoBRFileReferences class >> provinceDataWesternCoast [

	^ '/home/georges/Geo BR Atlas/data/Provinces Data - Anuire - Western Coast.csv'
]

{ #category : #accessing }
GeoBRFileReferences class >> provincesAnuire [

	^ '/home/georges/Geo BR Atlas/data/Provinces - Anuire.csv'
]

{ #category : #accessing }
GeoBRFileReferences class >> terrains [

	^ '/home/georges/Geo BR Atlas/data/Terrains.csv'
]

{ #category : #accessing }
GeoBRFileReferences class >> woods [

	^ '/home/georges/Geo BR Atlas/data/woods.svg'
]
