Class {
	#name : #GeoBRXMLLegend,
	#superclass : #GeoBRXMLConvertedObject,
	#instVars : [
		'id',
		'name',
		'domain'
	],
	#category : #'Geo-Birthright-Cerilia-Converting'
}

{ #category : #accessing }
GeoBRXMLLegend >> domain [

	^ domain
]

{ #category : #accessing }
GeoBRXMLLegend >> domain: anObject [

	domain := anObject
]

{ #category : #accessing }
GeoBRXMLLegend >> id [

	^ id
]

{ #category : #accessing }
GeoBRXMLLegend >> id: anObject [

	id := anObject
]

{ #category : #accessing }
GeoBRXMLLegend >> name [

	^ name
]

{ #category : #accessing }
GeoBRXMLLegend >> name: anObject [

	name := anObject
]
