Class {
	#name : #GeoBRConvertedDomain,
	#superclass : #GeoBRConvertedObject,
	#instVars : [
		'name',
		'abbriviation',
		'ruler',
		'goldbars',
		'court'
	],
	#category : #'Geo-Birthright-Cerilia-Converting'
}

{ #category : #accessing }
GeoBRConvertedDomain >> abbriviation [

	^ abbriviation
]

{ #category : #accessing }
GeoBRConvertedDomain >> abbriviation: anObject [

	abbriviation := anObject
]

{ #category : #accessing }
GeoBRConvertedDomain >> court [

	^ court
]

{ #category : #accessing }
GeoBRConvertedDomain >> court: anObject [

	court := anObject
]

{ #category : #accessing }
GeoBRConvertedDomain >> goldbars [

	^ goldbars
]

{ #category : #accessing }
GeoBRConvertedDomain >> goldbars: anObject [

	goldbars := anObject
]

{ #category : #accessing }
GeoBRConvertedDomain >> name [

	^ name
]

{ #category : #accessing }
GeoBRConvertedDomain >> name: anObject [

	name := anObject
]

{ #category : #accessing }
GeoBRConvertedDomain >> ruler [

	^ ruler
]

{ #category : #accessing }
GeoBRConvertedDomain >> ruler: anObject [

	ruler := anObject
]
