Class {
	#name : #GeoBRConvertedDeity,
	#superclass : #GeoBRConvertedObject,
	#instVars : [
		'name',
		'abbriviation',
		'type',
		'alignment'
	],
	#category : #'Geo-Birthright-Cerilia-Converting'
}

{ #category : #accessing }
GeoBRConvertedDeity >> abbriviation [

	^ abbriviation
]

{ #category : #accessing }
GeoBRConvertedDeity >> abbriviation: anObject [

	abbriviation := anObject
]

{ #category : #accessing }
GeoBRConvertedDeity >> alignment [

	^ alignment
]

{ #category : #accessing }
GeoBRConvertedDeity >> alignment: anObject [

	alignment := anObject
]

{ #category : #accessing }
GeoBRConvertedDeity >> name [

	^ name
]

{ #category : #accessing }
GeoBRConvertedDeity >> name: anObject [

	name := anObject
]

{ #category : #accessing }
GeoBRConvertedDeity >> type [

	^ type
]

{ #category : #accessing }
GeoBRConvertedDeity >> type: anObject [

	type := anObject
]
