Class {
	#name : #GeoBRConvertedProvinceData,
	#superclass : #GeoBRConvertedObject,
	#instVars : [
		'province',
		'domain',
		'population',
		'fortification',
		'law',
		'temples',
		'guilds',
		'sources',
		'race'
	],
	#category : #'Geo-Birthright-Converting'
}

{ #category : #accessing }
GeoBRConvertedProvinceData >> domain [

	^ domain
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> domain: anObject [

	domain := anObject
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> fortification [

	^ fortification
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> fortification: anObject [

	fortification := anObject
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> guilds [

	^ guilds
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> guilds: anObject [

	guilds := anObject
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> law [

	^ law
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> law: anObject [

	law := anObject
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> population [

	^ population
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> population: anObject [

	population := anObject
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> province [

	^ province
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> province: anObject [

	province := anObject
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> race [

	^ race
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> race: anObject [

	race := anObject
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> sources [

	^ sources
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> sources: anObject [

	sources := anObject
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> temples [

	^ temples
]

{ #category : #accessing }
GeoBRConvertedProvinceData >> temples: anObject [

	temples := anObject
]
