Class {
	#name : #GeoBRConvertedCharacter,
	#superclass : #GeoBRConvertedObject,
	#instVars : [
		'name',
		'gender',
		'race',
		'alignment',
		'faith',
		'bloodlineDerivation',
		'bloodlineStrength',
		'bloodlineScore',
		'rpSaved',
		'bloodAbilities',
		'classes',
		'skills',
		'lieutenantOf'
	],
	#category : #'Geo-Birthright-Converting'
}

{ #category : #accessing }
GeoBRConvertedCharacter >> alignment [

	^ alignment
]

{ #category : #accessing }
GeoBRConvertedCharacter >> alignment: anObject [

	alignment := anObject
]

{ #category : #accessing }
GeoBRConvertedCharacter >> bloodAbilities [

	^ bloodAbilities
]

{ #category : #accessing }
GeoBRConvertedCharacter >> bloodAbilities: anObject [

	bloodAbilities := anObject
]

{ #category : #accessing }
GeoBRConvertedCharacter >> bloodlineDerivation [

	^ bloodlineDerivation
]

{ #category : #accessing }
GeoBRConvertedCharacter >> bloodlineDerivation: anObject [

	bloodlineDerivation := anObject
]

{ #category : #accessing }
GeoBRConvertedCharacter >> bloodlineScore [

	^ bloodlineScore
]

{ #category : #accessing }
GeoBRConvertedCharacter >> bloodlineScore: anObject [

	bloodlineScore := anObject
]

{ #category : #accessing }
GeoBRConvertedCharacter >> bloodlineStrength [

	^ bloodlineStrength
]

{ #category : #accessing }
GeoBRConvertedCharacter >> bloodlineStrength: anObject [

	bloodlineStrength := anObject
]

{ #category : #accessing }
GeoBRConvertedCharacter >> classes [

	^ classes
]

{ #category : #accessing }
GeoBRConvertedCharacter >> classes: anObject [

	classes := anObject
]

{ #category : #accessing }
GeoBRConvertedCharacter >> faith [

	^ faith
]

{ #category : #accessing }
GeoBRConvertedCharacter >> faith: anObject [

	faith := anObject
]

{ #category : #accessing }
GeoBRConvertedCharacter >> gender [

	^ gender
]

{ #category : #accessing }
GeoBRConvertedCharacter >> gender: anObject [

	gender := anObject
]

{ #category : #accessing }
GeoBRConvertedCharacter >> lieutenantOf [

	^ lieutenantOf
]

{ #category : #accessing }
GeoBRConvertedCharacter >> lieutenantOf: anObject [

	lieutenantOf := anObject
]

{ #category : #accessing }
GeoBRConvertedCharacter >> name [

	^ name
]

{ #category : #accessing }
GeoBRConvertedCharacter >> name: anObject [

	name := anObject
]

{ #category : #accessing }
GeoBRConvertedCharacter >> race [

	^ race
]

{ #category : #accessing }
GeoBRConvertedCharacter >> race: anObject [

	race := anObject
]

{ #category : #accessing }
GeoBRConvertedCharacter >> rpSaved [

	^ rpSaved
]

{ #category : #accessing }
GeoBRConvertedCharacter >> rpSaved: anObject [

	rpSaved := anObject
]

{ #category : #accessing }
GeoBRConvertedCharacter >> skills [

	^ skills
]

{ #category : #accessing }
GeoBRConvertedCharacter >> skills: anObject [

	skills := anObject
]
